### PR TITLE
Trying to fix runtime warnings for sphinx

### PR DESCRIPTION
**Pull request by bsipocz**
I think this get rids of the runtime warnings (though may be sub-optimal at some places), but the build is still failing. To be honest I have no idea why it comes up on travis now (and not before), and why only on py3 and not 2.7.

### CODE REVIEW

**Comment by bsipocz** [comment]
OK, now I see it causes more trouble than it solves :(

https://travis-ci.org/bsipocz/gammapy/builds/110819089

**Comment by cdeil** [comment]
I don't think I like this way of fixing the significance computation or power-law computation issues.
I'll have a closer look and see if I cherry-pick your fix or come up with a seperate one.

Concerning the matplotlib change --- since when is cycler a required dependency for matplotlib? Do I have to declare this as a dependency of Gammapy? I'll cherry-pick that fix now.

**Comment by bsipocz** [comment]
@cdeil - Actually these changes made the tests fail while sphinx still fails, and I'm not really happy with any of those. The mpl warning was the first, but then even changing as advised in the warning message didn't get rid of the message.

**Comment by cdeil** [comment]
Thank you for all the work on this!
I know it takes a lot of time to debug this stuff.
Let me know if there's something I can maybe help you with sometime!

**Comment by bsipocz** [comment]
No worries, you already helped me a lot :) and I like to hunt for bugs like these (though better like it when they finally get found).

**Pull request closed without merging**
